# Generated by Django 4.0 on 2021-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MysiteSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_name', models.CharField(max_length=32, unique=True, verbose_name='系统名称')),
                ('sys_title', models.CharField(max_length=32, verbose_name='系统标题')),
                ('sys_url', models.CharField(max_length=128, verbose_name='系统连接')),
            ],
            options={
                'verbose_name': '系统',
                'verbose_name_plural': '系统',
            },
        ),
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='网站标题')),
                ('logo', models.CharField(max_length=128, verbose_name='网站logo')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
